[platformio]
default_envs = esp32dev

; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino

monitor_speed = 115200

build_src_filter =
    +<*>

build_flags =
    -I include
    -DCORE_DEBUG_LEVEL=3
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER=1
    -D TFT_WIDTH=128
    -D TFT_HEIGHT=160
    -D TFT_MISO=19
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=15
    -D TFT_DC=27 ; Chân A0 (DC / Data Command) của màn hình TFT ST7735
    -D TFT_RST=4
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SPI_FREQUENCY=27000000

lib_deps =
    knolleary/PubSubClient@2.8
    bodmer/TFT_eSPI@^2.5.43

[env:gateway_synthetic]
extends = env:esp32dev
build_flags = ${env:esp32dev.build_flags} -DGATEWAY_SENSOR_MODE=2

[env:gateway_hardware]
extends = env:esp32dev
build_flags = ${env:esp32dev.build_flags} -DGATEWAY_SENSOR_MODE=1

[env:gateway_hardware_gps]
extends = env:esp32dev
build_flags = ${env:esp32dev.build_flags} -DGATEWAY_SENSOR_MODE=1 -DGATEWAY_GPS_ENABLED=1

[env:gateway_wdt_test]
extends = env:esp32dev
build_flags = ${env:esp32dev.build_flags} -DGATEWAY_TEST_WDT_STALL=1
