#pragma once
#define MQTT_TOPIC_DASHBOARD "aiot/2026/gateway/data"
#define MQTT_TEST_TOPIC_DASHBOARD "aiot/2026/test/gateway/data"
#define GATEWAY_DASHBOARD_PERIOD_MS 5000UL
#define GATEWAY_DASHBOARD_JSON_CAPACITY 4096
#define GATEWAY_DASHBOARD_MQTT_BUFFER_SIZE 4352
